### ISSUE TITLE
No file output with concat option set to false

### ISSUE THREAD

**Issue by embpdaniel** [kenzanlabs/pipeline-minify-js#13]
Expected that setting concat to false would export individual minimized .js files to `./dist/build/components/`:

```javascript
var componentJsFiles = ['src/components/webui.js', './src/components/*/**/*-module.js', './src/components/*/**/*.js', '!./src/components/**/**/*.test.js'];

var minifyOptions = {
    addSourceMaps: false,
    concat: false
  };

  //all component js individually copied and minified
  var componentJsStreamMin = plugins.gulp.src(componentJsFiles)
    .pipe(jsMinifyPipeline(minifyOptions).minifyJS())
    .pipe(gulp.dest('./dist/build/components/'));

```

However it does not output any files at all. Setting concat back to true outputs a single minimized and concatenated file, to `./dist/build/components/`, as expected.

**Comment by cxoltero** [comment]
when recreating the issue, tested within local project as well as different other projects. Bug is not present on either of those environments. 

'gulp.task('build', ['clean', 'validate'] , function() {
  return gulp
    .src(config.jsFiles)
    .pipe(minifyPipeline({concat: true, addSourceMaps: false}).minifyJS())
    .pipe(gulp.dest('dist'));
});'

![screenshot 2016-04-21 11 57 50](https://cloud.githubusercontent.com/assets/7050734/14716339/9b2f174c-07ba-11e6-8c0d-80ac949b3087.png)

'gulp.task('buildMaps', ['clean', 'validate'] , function() {
  return gulp
    .src(config.jsFiles)
    .pipe(minifyPipeline({concat: true, addSourceMaps: true}).minifyJS())
    .pipe(gulp.dest('dist'));
});
'

![screenshot 2016-04-21 11 59 46](https://cloud.githubusercontent.com/assets/7050734/14716341/9b3103e0-07ba-11e6-9f40-3f5c3f56e1d1.png)

'
gulp.task('buildFalse', ['clean', 'validate'] , function() {

  return gulp
    .src(config.jsFiles)
    .pipe(minifyPipeline({concat: false, addSourceMaps: false}).minifyJS())
    .pipe(gulp.dest('dist'));
});
'

![screenshot 2016-04-21 12 00 33](https://cloud.githubusercontent.com/assets/7050734/14716340/9b304b8a-07ba-11e6-898c-80ab2e288a17.png)

**Comment by obuckley-kenzan** [comment]
@embpdaniel 
Can you please share your versions of node and npm respectively?  eg. 
```bash
$ node -v
$ npm -v
```

**Comment by embpdaniel** [comment]
@obuckley-kenzan node v 4.4.2, npm v 2.15.0

**Comment by obuckley-kenzan** [comment]
@embpdaniel , please work with @cxoltero to provide the simplest set of files needed to reproduce the issue as a dummy project (as a zip maybe?) and we can start troubleshooting.

Thanks!

**Comment by embpdaniel** [comment]
@obuckley-kenzan While setting up a test for @cxoltero, reinstalling the minify library and setting it up, I noticed the individual files were now copying minified as expected. Things are working fine, maybe there were other factors involved in our first run. For now I think it's safe to close this ticket.

**Comment by obuckley-kenzan** [comment]
great, glad to hear it is working for you now @embpdaniel ! thanks to both of you for working through the issue
