### ISSUE TITLE
update README.md to show changes on issue#18 and issue#19

### ISSUE THREAD

**Issue by cxoltero** [kenzanlabs/pipeline-minify-js#21]
Readme should show the changes made from issue#18 and issue#19

**Comment by obuckley-kenzan** [comment]
thanks @cxoltero , but this should already be part of those changes themselves.  Per the CONTRIBUTING.md, no. 8 
https://github.com/kenzanlabs/keystone/blob/master/CONTRIBUTING.md#pull-requests
